### ISSUE TITLE
Raspberry config for Bossac gives Error, file not found

### ISSUE THREAD

**Issue by Toogo** [Tircown/ERCF-easy-brd#13]
When trying to install, teher are erros saying file does not exists:
So make is not working 

sudo apt install libreadline-dev libwxgtk3.0-*
git clone https://github.com/shumatech/BOSSA.git
cd BOSSA
make

Is there a solution so I can let the Rabbit work?

Frank

**Comment by Tircown** [comment]
Can you share a screenshot of the console log when doing the setup please. Or at least the exact error message and previous commands.
