### ISSUE TITLE
Unable to read tmc uart 'selector_stepper' register DRV_STATUS

### ISSUE THREAD

**Issue by hushilin** [Tircown/ERCF-easy-brd#14]
The success of “gear_stepper”
Unable to read tmc uart 'selector_stepper' register DRV_STATUS

**Comment by Tircown** [comment]
This is not an issue related to the design of the board but a faulty one or the stepper drivers or whatever.
Github is not the right place for your problem, ask for help on the Voron discord, channel ercf please.

Thanks
