### ISSUE TITLE
different wiring MS1 / MS2

### ISSUE THREAD

**Issue by Fragmon** [Tircown/ERCF-easy-brd#18]
Hello,

i look into the pcb and see that one tmc driver is set gnd/gnd (8 Microsteps) and the other gnd/vcc (16 Microsteps. But both stepper are set with 16 microsteps in the config. Can you explain, why you set the tmc to this different microsteps?

**Comment by Tircown** [comment]
Hello,
It's wired for UART, not standalone mode. MS1 and MS2 are used for UART address and so are different for each driver. Microsteps are set by firmware config.
